// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RealWorldCommon.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GenericErrorModel
    {
        /// <summary>
        /// Initializes a new instance of the GenericErrorModel class.
        /// </summary>
        public GenericErrorModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GenericErrorModel class.
        /// </summary>
        public GenericErrorModel(GenericErrorModelErrors errors)
        {
            Errors = errors;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errors")]
        public GenericErrorModelErrors Errors { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Errors == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Errors");
            }
            if (Errors != null)
            {
                Errors.Validate();
            }
        }
    }
}
