// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RealWorldCommon.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LoginUserRequest
    {
        /// <summary>
        /// Initializes a new instance of the LoginUserRequest class.
        /// </summary>
        public LoginUserRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LoginUserRequest class.
        /// </summary>
        public LoginUserRequest(LoginUserModel user)
        {
            User = user;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "user")]
        public LoginUserModel User { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (User == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "User");
            }
            if (User != null)
            {
                User.Validate();
            }
        }
    }
}
