// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RealWorldCommon.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MultipleArticlesResponse
    {
        /// <summary>
        /// Initializes a new instance of the MultipleArticlesResponse class.
        /// </summary>
        public MultipleArticlesResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MultipleArticlesResponse class.
        /// </summary>
        public MultipleArticlesResponse(IList<ArticleModel> articles, int articlesCount)
        {
            Articles = articles;
            ArticlesCount = articlesCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "articles")]
        public IList<ArticleModel> Articles { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "articlesCount")]
        public int ArticlesCount { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Articles == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Articles");
            }
            if (Articles != null)
            {
                foreach (var element in Articles)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
