// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RealWorldCommon.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProfileResponse
    {
        /// <summary>
        /// Initializes a new instance of the ProfileResponse class.
        /// </summary>
        public ProfileResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProfileResponse class.
        /// </summary>
        public ProfileResponse(ProfileModel profile)
        {
            Profile = profile;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "profile")]
        public ProfileModel Profile { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Profile == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Profile");
            }
            if (Profile != null)
            {
                Profile.Validate();
            }
        }
    }
}
