// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RealWorldCommon.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SingleCommentResponse
    {
        /// <summary>
        /// Initializes a new instance of the SingleCommentResponse class.
        /// </summary>
        public SingleCommentResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SingleCommentResponse class.
        /// </summary>
        public SingleCommentResponse(CommentModel comment)
        {
            Comment = comment;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "comment")]
        public CommentModel Comment { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Comment == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Comment");
            }
            if (Comment != null)
            {
                Comment.Validate();
            }
        }
    }
}
