// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RealWorldCommon.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UpdateUserModel
    {
        /// <summary>
        /// Initializes a new instance of the UpdateUser class.
        /// </summary>
        public UpdateUserModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpdateUser class.
        /// </summary>
        public UpdateUserModel(string email = default(string), string token = default(string), string username = default(string), string bio = default(string), string image = default(string))
        {
            Email = email;
            Token = token;
            Username = username;
            Bio = bio;
            Image = image;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "token")]
        public string Token { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "username")]
        public string Username { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bio")]
        public string Bio { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image")]
        public string Image { get; set; }

    }
}
